"""
PacketVision Pro - Database Module
====================================

Provides SQLite-based storage for captured packets, security alerts,
statistics snapshots, and application settings.

The database is designed for fast writes during live capture and efficient
queries for the GUI display. Indexed columns ensure quick lookups by
IP address, port, protocol, and timestamp.

Tables:
    packets     - Stores all captured packet metadata and decoded protocol fields
    alerts      - Security alerts generated by the threat detection engine
    statistics  - Periodic snapshots of capture statistics for historical trends
    settings    - Application configuration (key-value store)

Thread Safety:
    All database operations use a reentrant lock (threading.RLock) to allow
    safe concurrent access from the capture thread and GUI thread.

Usage:
    db = PacketDatabase("capture.db")
    db.insert_packet(packet_data)
    packets = db.get_packets(limit=100, filters={"protocol_name": "TCP"})
    stats = db.get_statistics()
"""

import sqlite3
import logging
import threading
from datetime import datetime
from typing import List, Dict, Any, Optional, Tuple
from pathlib import Path
from contextlib import contextmanager
import json

logger = logging.getLogger(__name__)


class PacketDatabase:
    """SQLite database manager for packet storage and retrieval."""

    SCHEMA = """
    CREATE TABLE IF NOT EXISTS packets (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp REAL NOT NULL,
        timestamp_str TEXT NOT NULL,
        src_mac TEXT,
        dst_mac TEXT,
        eth_type TEXT,
        src_ip TEXT,
        dst_ip TEXT,
        ip_version INTEGER,
        ip_protocol INTEGER,
        ip_ttl INTEGER,
        ip_length INTEGER,
        src_port INTEGER,
        dst_port INTEGER,
        tcp_flags TEXT,
        tcp_seq INTEGER,
        tcp_ack INTEGER,
        tcp_window INTEGER,
        udp_length INTEGER,
        icmp_type INTEGER,
        icmp_code INTEGER,
        arp_op INTEGER,
        arp_sender_ip TEXT,
        arp_target_ip TEXT,
        dns_query TEXT,
        dns_qtype INTEGER,
        http_method TEXT,
        http_host TEXT,
        http_path TEXT,
        http_status INTEGER,
        raw_data BLOB,
        packet_length INTEGER,
        protocol_name TEXT,
        src_country TEXT,
        dst_country TEXT,
        is_suspicious INTEGER DEFAULT 0,
        threat_type TEXT,
        threat_details TEXT
    );

    CREATE INDEX IF NOT EXISTS idx_timestamp ON packets(timestamp);
    CREATE INDEX IF NOT EXISTS idx_src_ip ON packets(src_ip);
    CREATE INDEX IF NOT EXISTS idx_dst_ip ON packets(dst_ip);
    CREATE INDEX IF NOT EXISTS idx_src_port ON packets(src_port);
    CREATE INDEX IF NOT EXISTS idx_dst_port ON packets(dst_port);
    CREATE INDEX IF NOT EXISTS idx_protocol ON packets(protocol_name);
    CREATE INDEX IF NOT EXISTS idx_suspicious ON packets(is_suspicious);
    CREATE INDEX IF NOT EXISTS idx_src_dst ON packets(src_ip, dst_ip);
    """

    STATS_SCHEMA = """
    CREATE TABLE IF NOT EXISTS statistics (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp REAL NOT NULL,
        total_packets INTEGER DEFAULT 0,
        total_bytes INTEGER DEFAULT 0,
        tcp_count INTEGER DEFAULT 0,
        udp_count INTEGER DEFAULT 0,
        icmp_count INTEGER DEFAULT 0,
        arp_count INTEGER DEFAULT 0,
        dns_count INTEGER DEFAULT 0,
        http_count INTEGER DEFAULT 0,
        suspicious_count INTEGER DEFAULT 0,
        unique_src_ips INTEGER DEFAULT 0,
        unique_dst_ips INTEGER DEFAULT 0,
        top_src_ip TEXT,
        top_dst_ip TEXT,
        top_src_port INTEGER,
        top_dst_port INTEGER
    );

    CREATE INDEX IF NOT EXISTS idx_stats_time ON statistics(timestamp);
    """

    ALERTS_SCHEMA = """
    CREATE TABLE IF NOT EXISTS alerts (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp REAL NOT NULL,
        timestamp_str TEXT NOT NULL,
        alert_type TEXT NOT NULL,
        severity TEXT NOT NULL,
        src_ip TEXT,
        dst_ip TEXT,
        src_port INTEGER,
        dst_port INTEGER,
        description TEXT,
        packet_count INTEGER DEFAULT 1,
        details TEXT,
        acknowledged INTEGER DEFAULT 0
    );

    CREATE INDEX IF NOT EXISTS idx_alerts_time ON alerts(timestamp);
    CREATE INDEX IF NOT EXISTS idx_alerts_type ON alerts(alert_type);
    CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity);
    """

    SETTINGS_SCHEMA = """
    CREATE TABLE IF NOT EXISTS settings (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL,
        updated_at REAL NOT NULL
    );
    """

    def __init__(self, db_path: str = "packetvision.db"):
        self.db_path = Path(db_path).resolve()
        self._lock = threading.RLock()
        self._init_db()
        logger.info(f"Database initialized at {self.db_path}")

    def _init_db(self):
        with self._lock:
            conn = sqlite3.connect(self.db_path)
            try:
                conn.executescript(self.SCHEMA)
                conn.executescript(self.STATS_SCHEMA)
                conn.executescript(self.ALERTS_SCHEMA)
                conn.executescript(self.SETTINGS_SCHEMA)
                conn.commit()
            finally:
                conn.close()

    @contextmanager
    def _get_conn(self):
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        try:
            yield conn
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()

    def insert_packet(self, packet_data: Dict[str, Any]) -> int:
        """Insert a packet into the database."""
        fields = [
            'timestamp', 'timestamp_str', 'src_mac', 'dst_mac', 'eth_type',
            'src_ip', 'dst_ip', 'ip_version', 'ip_protocol', 'ip_ttl',
            'ip_length', 'src_port', 'dst_port', 'tcp_flags', 'tcp_seq',
            'tcp_ack', 'tcp_window', 'udp_length', 'icmp_type', 'icmp_code',
            'arp_op', 'arp_sender_ip', 'arp_target_ip', 'dns_query', 'dns_qtype',
            'http_method', 'http_host', 'http_path', 'http_status',
            'raw_data', 'packet_length', 'protocol_name', 'src_country',
            'dst_country', 'is_suspicious', 'threat_type', 'threat_details'
        ]

        values = [packet_data.get(f) for f in fields]
        placeholders = ', '.join(['?' for _ in fields])
        columns = ', '.join(fields)

        with self._get_conn() as conn:
            cursor = conn.execute(
                f"INSERT INTO packets ({columns}) VALUES ({placeholders})",
                values
            )
            return cursor.lastrowid

    def insert_packets_batch(self, packets: List[Dict[str, Any]]) -> int:
        """Insert multiple packets efficiently."""
        if not packets:
            return 0

        fields = [
            'timestamp', 'timestamp_str', 'src_mac', 'dst_mac', 'eth_type',
            'src_ip', 'dst_ip', 'ip_version', 'ip_protocol', 'ip_ttl',
            'ip_length', 'src_port', 'dst_port', 'tcp_flags', 'tcp_seq',
            'tcp_ack', 'tcp_window', 'udp_length', 'icmp_type', 'icmp_code',
            'arp_op', 'arp_sender_ip', 'arp_target_ip', 'dns_query', 'dns_qtype',
            'http_method', 'http_host', 'http_path', 'http_status',
            'raw_data', 'packet_length', 'protocol_name', 'src_country',
            'dst_country', 'is_suspicious', 'threat_type', 'threat_details'
        ]

        values_list = [[p.get(f) for f in fields] for p in packets]
        placeholders = ', '.join(['?' for _ in fields])
        columns = ', '.join(fields)

        with self._get_conn() as conn:
            conn.executemany(
                f"INSERT INTO packets ({columns}) VALUES ({placeholders})",
                values_list
            )
            return len(packets)

    def get_packets(
        self,
        limit: int = 1000,
        offset: int = 0,
        filters: Optional[Dict[str, Any]] = None,
        order_by: str = "timestamp DESC"
    ) -> List[Dict[str, Any]]:
        """Retrieve packets with optional filters."""
        where_clauses = []
        params = []

        if filters:
            for key, value in filters.items():
                if value is not None:
                    if isinstance(value, (list, tuple)):
                        placeholders = ', '.join(['?' for _ in value])
                        where_clauses.append(f"{key} IN ({placeholders})")
                        params.extend(value)
                    elif isinstance(value, str) and '%' in value:
                        where_clauses.append(f"{key} LIKE ?")
                        params.append(value)
                    else:
                        where_clauses.append(f"{key} = ?")
                        params.append(value)

        where_clause = f"WHERE {' AND '.join(where_clauses)}" if where_clauses else ""

        query = f"""
            SELECT * FROM packets
            {where_clause}
            ORDER BY {order_by}
            LIMIT ? OFFSET ?
        """
        params.extend([limit, offset])

        with self._get_conn() as conn:
            cursor = conn.execute(query, params)
            return [dict(row) for row in cursor.fetchall()]

    def get_packet_count(self, filters: Optional[Dict[str, Any]] = None) -> int:
        """Get total packet count with optional filters."""
        where_clauses = []
        params = []

        if filters:
            for key, value in filters.items():
                if value is not None:
                    if isinstance(value, (list, tuple)):
                        placeholders = ', '.join(['?' for _ in value])
                        where_clauses.append(f"{key} IN ({placeholders})")
                        params.extend(value)
                    else:
                        where_clauses.append(f"{key} = ?")
                        params.append(value)

        where_clause = f"WHERE {' AND '.join(where_clauses)}" if where_clauses else ""

        with self._get_conn() as conn:
            cursor = conn.execute(
                f"SELECT COUNT(*) FROM packets {where_clause}", params
            )
            return cursor.fetchone()[0]

    def get_packet_by_id(self, packet_id: int) -> Optional[Dict[str, Any]]:
        """Get a single packet by ID."""
        with self._get_conn() as conn:
            cursor = conn.execute("SELECT * FROM packets WHERE id = ?", (packet_id,))
            row = cursor.fetchone()
            return dict(row) if row else None

    def get_statistics(self) -> Dict[str, Any]:
        """Get overall packet statistics."""
        with self._get_conn() as conn:
            stats = {}
            cursor = conn.execute("""
                SELECT 
                    COUNT(*) as total_packets,
                    SUM(packet_length) as total_bytes,
                    COUNT(DISTINCT src_ip) as unique_src_ips,
                    COUNT(DISTINCT dst_ip) as unique_dst_ips,
                    SUM(CASE WHEN protocol_name = 'TCP' THEN 1 ELSE 0 END) as tcp_count,
                    SUM(CASE WHEN protocol_name = 'UDP' THEN 1 ELSE 0 END) as udp_count,
                    SUM(CASE WHEN protocol_name = 'ICMP' THEN 1 ELSE 0 END) as icmp_count,
                    SUM(CASE WHEN protocol_name = 'ARP' THEN 1 ELSE 0 END) as arp_count,
                    SUM(CASE WHEN protocol_name = 'DNS' THEN 1 ELSE 0 END) as dns_count,
                    SUM(CASE WHEN protocol_name = 'HTTP' THEN 1 ELSE 0 END) as http_count,
                    SUM(is_suspicious) as suspicious_count
                FROM packets
            """)
            stats = dict(cursor.fetchone())

            # Top IPs and ports
            cursor = conn.execute("""
                SELECT src_ip, COUNT(*) as cnt FROM packets
                WHERE src_ip IS NOT NULL
                GROUP BY src_ip ORDER BY cnt DESC LIMIT 1
            """)
            row = cursor.fetchone()
            stats['top_src_ip'] = row['src_ip'] if row else None

            cursor = conn.execute("""
                SELECT dst_ip, COUNT(*) as cnt FROM packets
                WHERE dst_ip IS NOT NULL
                GROUP BY dst_ip ORDER BY cnt DESC LIMIT 1
            """)
            row = cursor.fetchone()
            stats['top_dst_ip'] = row['dst_ip'] if row else None

            cursor = conn.execute("""
                SELECT src_port, COUNT(*) as cnt FROM packets
                WHERE src_port IS NOT NULL
                GROUP BY src_port ORDER BY cnt DESC LIMIT 1
            """)
            row = cursor.fetchone()
            stats['top_src_port'] = row['src_port'] if row else None

            cursor = conn.execute("""
                SELECT dst_port, COUNT(*) as cnt FROM packets
                WHERE dst_port IS NOT NULL
                GROUP BY dst_port ORDER BY cnt DESC LIMIT 1
            """)
            row = cursor.fetchone()
            stats['top_dst_port'] = row['dst_port'] if row else None

            return stats

    def get_protocol_distribution(self) -> List[Dict[str, Any]]:
        """Get protocol distribution statistics."""
        with self._get_conn() as conn:
            cursor = conn.execute("""
                SELECT protocol_name, COUNT(*) as count, SUM(packet_length) as bytes
                FROM packets
                WHERE protocol_name IS NOT NULL
                GROUP BY protocol_name
                ORDER BY count DESC
            """)
            return [dict(row) for row in cursor.fetchall()]

    def get_top_talkers(self, limit: int = 10) -> List[Dict[str, Any]]:
        """Get top talkers (source IPs by packet count)."""
        with self._get_conn() as conn:
            cursor = conn.execute("""
                SELECT src_ip, COUNT(*) as packets, SUM(packet_length) as bytes
                FROM packets
                WHERE src_ip IS NOT NULL
                GROUP BY src_ip
                ORDER BY packets DESC
                LIMIT ?
            """, (limit,))
            return [dict(row) for row in cursor.fetchall()]

    def get_top_conversations(self, limit: int = 10) -> List[Dict[str, Any]]:
        """Get top conversations (src_ip -> dst_ip)."""
        with self._get_conn() as conn:
            cursor = conn.execute("""
                SELECT src_ip, dst_ip, COUNT(*) as packets, SUM(packet_length) as bytes
                FROM packets
                WHERE src_ip IS NOT NULL AND dst_ip IS NOT NULL
                GROUP BY src_ip, dst_ip
                ORDER BY packets DESC
                LIMIT ?
            """, (limit,))
            return [dict(row) for row in cursor.fetchall()]

    def get_port_distribution(self, protocol: str = 'TCP', limit: int = 20) -> List[Dict[str, Any]]:
        """Get port distribution for a protocol."""
        port_col = 'dst_port' if protocol in ('TCP', 'UDP') else 'dst_port'
        with self._get_conn() as conn:
            cursor = conn.execute(f"""
                SELECT {port_col} as port, COUNT(*) as count
                FROM packets
                WHERE protocol_name = ? AND {port_col} IS NOT NULL
                GROUP BY {port_col}
                ORDER BY count DESC
                LIMIT ?
            """, (protocol, limit))
            return [dict(row) for row in cursor.fetchall()]

    def get_timeline_data(self, interval_seconds: int = 60, limit: int = 100) -> List[Dict[str, Any]]:
        """Get packet timeline data grouped by time intervals."""
        with self._get_conn() as conn:
            cursor = conn.execute(f"""
                SELECT 
                    CAST(timestamp / ? AS INTEGER) * ? as interval_start,
                    COUNT(*) as packet_count,
                    SUM(packet_length) as byte_count
                FROM packets
                GROUP BY interval_start
                ORDER BY interval_start DESC
                LIMIT ?
            """, (interval_seconds, interval_seconds, limit))
            return [dict(row) for row in cursor.fetchall()]

    def insert_alert(self, alert: Dict[str, Any]) -> int:
        """Insert a security alert."""
        with self._get_conn() as conn:
            cursor = conn.execute("""
                INSERT INTO alerts (timestamp, timestamp_str, alert_type, severity,
                                   src_ip, dst_ip, src_port, dst_port,
                                   description, packet_count, details)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                alert.get('timestamp'), alert.get('timestamp_str'),
                alert.get('alert_type'), alert.get('severity'),
                alert.get('src_ip'), alert.get('dst_ip'),
                alert.get('src_port'), alert.get('dst_port'),
                alert.get('description'), alert.get('packet_count', 1),
                alert.get('details')
            ))
            return cursor.lastrowid

    def get_alerts(
        self,
        limit: int = 100,
        offset: int = 0,
        severity: Optional[str] = None,
        alert_type: Optional[str] = None,
        acknowledged: Optional[bool] = None
    ) -> List[Dict[str, Any]]:
        """Get security alerts with filters."""
        where_clauses = []
        params = []

        if severity:
            where_clauses.append("severity = ?")
            params.append(severity)
        if alert_type:
            where_clauses.append("alert_type = ?")
            params.append(alert_type)
        if acknowledged is not None:
            where_clauses.append("acknowledged = ?")
            params.append(int(acknowledged))

        where_clause = f"WHERE {' AND '.join(where_clauses)}" if where_clauses else ""

        query = f"""
            SELECT * FROM alerts
            {where_clause}
            ORDER BY timestamp DESC
            LIMIT ? OFFSET ?
        """
        params.extend([limit, offset])

        with self._get_conn() as conn:
            cursor = conn.execute(query, params)
            return [dict(row) for row in cursor.fetchall()]

    def acknowledge_alert(self, alert_id: int) -> bool:
        """Mark an alert as acknowledged."""
        with self._get_conn() as conn:
            cursor = conn.execute(
                "UPDATE alerts SET acknowledged = 1 WHERE id = ?", (alert_id,)
            )
            return cursor.rowcount > 0

    def save_statistics(self, stats: Dict[str, Any]) -> int:
        """Save periodic statistics snapshot."""
        with self._get_conn() as conn:
            cursor = conn.execute("""
                INSERT INTO statistics (timestamp, total_packets, total_bytes,
                    tcp_count, udp_count, icmp_count, arp_count, dns_count,
                    http_count, suspicious_count, unique_src_ips, unique_dst_ips,
                    top_src_ip, top_dst_ip, top_src_port, top_dst_port)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                stats.get('timestamp'), stats.get('total_packets', 0),
                stats.get('total_bytes', 0), stats.get('tcp_count', 0),
                stats.get('udp_count', 0), stats.get('icmp_count', 0),
                stats.get('arp_count', 0), stats.get('dns_count', 0),
                stats.get('http_count', 0), stats.get('suspicious_count', 0),
                stats.get('unique_src_ips', 0), stats.get('unique_dst_ips', 0),
                stats.get('top_src_ip'), stats.get('top_dst_ip'),
                stats.get('top_src_port'), stats.get('top_dst_port')
            ))
            return cursor.lastrowid

    def get_statistics_history(self, limit: int = 100) -> List[Dict[str, Any]]:
        """Get historical statistics."""
        with self._get_conn() as conn:
            cursor = conn.execute("""
                SELECT * FROM statistics ORDER BY timestamp DESC LIMIT ?
            """, (limit,))
            return [dict(row) for row in cursor.fetchall()]

    def set_setting(self, key: str, value: str):
        """Save a setting."""
        with self._get_conn() as conn:
            conn.execute("""
                INSERT OR REPLACE INTO settings (key, value, updated_at)
                VALUES (?, ?, ?)
            """, (key, value, datetime.now().timestamp()))

    def get_setting(self, key: str, default: str = "") -> str:
        """Get a setting."""
        with self._get_conn() as conn:
            cursor = conn.execute("SELECT value FROM settings WHERE key = ?", (key,))
            row = cursor.fetchone()
            return row['value'] if row else default

    def clear_packets(self, before_timestamp: Optional[float] = None) -> int:
        """Clear old packets."""
        with self._get_conn() as conn:
            if before_timestamp:
                cursor = conn.execute(
                    "DELETE FROM packets WHERE timestamp < ?", (before_timestamp,)
                )
            else:
                cursor = conn.execute("DELETE FROM packets")
            return cursor.rowcount

    def vacuum(self):
        """Vacuum database to reclaim space."""
        with self._get_conn() as conn:
            conn.execute("VACUUM")

    def export_to_csv(self, filepath: str, filters: Optional[Dict] = None, limit: int = 10000):
        """Export packets to CSV."""
        import csv
        packets = self.get_packets(limit=limit, filters=filters)
        
        if not packets:
            return 0

        fieldnames = packets[0].keys()
        with open(filepath, 'w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(packets)
        
        return len(packets)

    def get_db_info(self) -> Dict[str, Any]:
        """Get database info."""
        with self._get_conn() as conn:
            cursor = conn.execute("SELECT COUNT(*) as count FROM packets")
            packet_count = cursor.fetchone()['count']
            
            cursor = conn.execute("SELECT COUNT(*) as count FROM alerts")
            alert_count = cursor.fetchone()['count']
            
            cursor = conn.execute("SELECT page_count * page_size as size FROM pragma_page_count(), pragma_page_size()")
            size = cursor.fetchone()['size']
            
            return {
                'path': str(self.db_path),
                'packet_count': packet_count,
                'alert_count': alert_count,
                'size_bytes': size,
                'size_mb': round(size / (1024 * 1024), 2)
            }
