"""
PacketVision Pro - Auto PDF Report Generator
==============================================

Generates a professional PDF capture report when the application closes.
The report includes:

    - Tool header (name, version, creator, website)
    - Capture session summary (start/end time, duration, interface)
    - Protocol distribution breakdown
    - Threat detection summary
    - Full packet table (up to 500 rows for readability)
    - Top talkers (source and destination IPs)

Reports are saved to the user's Documents folder (or project directory
as fallback) with timestamped filenames.
"""

import os
import logging
from datetime import datetime
from pathlib import Path
from collections import defaultdict
from typing import Dict, Any, List, Optional

try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False

logger = logging.getLogger(__name__)


class CaptureReportPDF(FPDF):
    """Custom PDF class for PacketVision Pro capture reports."""

    TOOL_NAME = "PacketVision Pro"
    TOOL_VERSION = "1.0.0"
    TOOL_DESCRIPTION = "Advanced Network Packet Sniffer & Analyzer"
    CREATOR = "Sifuna Codex"
    TOOLBSITE = "https://github.com/aasz253/CodeAlpha_PacketVision-Pro"

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        """Page header with tool branding."""
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, f'{self.TOOL_NAME} v{self.TOOL_VERSION} - Capture Report', align='L')
        self.cell(0, 6, f'Page {self.page_no()}/{{nb}}', align='R', new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        """Page footer."""
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Generated by {self.TOOL_NAME} | Created by {self.CREATOR} | {self.TOOLBSITE}', align='C')

    def title_block(self):
        """Render the cover/title section."""
        self.set_font('Helvetica', 'B', 22)
        self.set_text_color(30, 30, 30)
        self.cell(0, 14, self.TOOL_NAME, align='C', new_x="LMARGIN", new_y="NEXT")

        self.set_font('Helvetica', '', 12)
        self.set_text_color(80, 80, 80)
        self.cell(0, 8, self.TOOL_DESCRIPTION, align='C', new_x="LMARGIN", new_y="NEXT")

        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, f'Created by {self.CREATOR}', align='C', new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 6, f'{self.TOOLBSITE}', align='C', new_x="LMARGIN", new_y="NEXT")
        self.ln(8)

        self.set_draw_color(50, 50, 50)
        self.set_line_width(0.5)
        self.line(30, self.get_y(), 180, self.get_y())
        self.set_line_width(0.2)
        self.ln(10)

    def section_header(self, title: str):
        """Render a section header."""
        self.set_font('Helvetica', 'B', 13)
        self.set_text_color(30, 30, 30)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(50, 120, 200)
        self.set_line_width(0.4)
        self.line(10, self.get_y(), 80, self.get_y())
        self.set_line_width(0.2)
        self.ln(4)

    def kv_row(self, key: str, value: str, bold_value=False):
        """Render a key-value row."""
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(60, 60, 60)
        self.cell(55, 7, key)
        self.set_font('Helvetica', 'B' if bold_value else '', 10)
        self.set_text_color(30, 30, 30)
        self.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")


def generate_report(
    packets: List[Dict[str, Any]],
    alerts: Optional[List[Dict[str, Any]]] = None,
    interface: str = "unknown",
    start_time: Optional[float] = None,
    end_time: Optional[float] = None,
    output_dir: Optional[str] = None,
) -> Optional[str]:
    """
    Generate a PDF capture report and save it to disk.

    Args:
        packets: List of packet dictionaries from the capture session.
        alerts: List of alert dictionaries (optional).
        interface: Network interface used for capture.
        start_time: Capture start timestamp (epoch).
        end_time: Capture end timestamp (epoch).
        output_dir: Directory to save the report. Defaults to Documents/.

    Returns:
        Path to the saved PDF file, or None on failure.
    """
    if not HAS_FPDF:
        logger.warning("fpdf2 not installed. PDF report not generated. Install with: pip install fpdf2")
        return None

    if not packets:
        logger.info("No packets captured. Skipping PDF report generation.")
        return None

    try:
        pdf = CaptureReportPDF()
        pdf.alias_nb_pages()
        pdf.add_page()

        # === TITLE ===
        pdf.title_block()

        # === SESSION INFO ===
        pdf.section_header("Capture Session")

        if start_time:
            start_dt = datetime.fromtimestamp(start_time)
            pdf.kv_row("Start Time:", start_dt.strftime('%Y-%m-%d %H:%M:%S'))
        if end_time:
            end_dt = datetime.fromtimestamp(end_time)
            pdf.kv_row("End Time:", end_dt.strftime('%Y-%m-%d %H:%M:%S'))
        if start_time and end_time:
            duration = end_time - start_time
            mins, secs = divmod(int(duration), 60)
            hours, mins = divmod(mins, 60)
            pdf.kv_row("Duration:", f"{hours}h {mins}m {secs}s" if hours else f"{mins}m {secs}s")

        pdf.kv_row("Interface:", interface)
        pdf.kv_row("Total Packets:", f"{len(packets):,}")
        total_bytes = sum(p.get('packet_length', 0) for p in packets)
        pdf.kv_row("Total Bytes:", _format_bytes(total_bytes))
        pdf.kv_row("Report Generated:", datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
        pdf.ln(4)

        # === PROTOCOL DISTRIBUTION ===
        proto_counts = defaultdict(int)
        for pkt in packets:
            proto_counts[pkt.get('protocol_name', 'Unknown')] += 1

        pdf.section_header("Protocol Distribution")
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_fill_color(50, 120, 200)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(40, 7, 'Protocol', border=1, fill=True, align='C')
        pdf.cell(30, 7, 'Count', border=1, fill=True, align='C')
        pdf.cell(30, 7, 'Bytes', border=1, fill=True, align='C')
        pdf.cell(30, 7, 'Percentage', border=1, fill=True, align='C', new_x="LMARGIN", new_y="NEXT")

        proto_bytes = defaultdict(int)
        for pkt in packets:
            proto_bytes[pkt.get('protocol_name', 'Unknown')] += pkt.get('packet_length', 0)

        pdf.set_font('Helvetica', '', 9)
        pdf.set_text_color(30, 30, 30)
        for proto, count in sorted(proto_counts.items(), key=lambda x: -x[1]):
            pct = (count / len(packets) * 100) if packets else 0
            pdf.cell(40, 6, proto, border=1, align='C')
            pdf.cell(30, 6, f'{count:,}', border=1, align='C')
            pdf.cell(30, 6, _format_bytes(proto_bytes[proto]), border=1, align='C')
            pdf.cell(30, 6, f'{pct:.1f}%', border=1, align='C', new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        # === THREAT SUMMARY ===
        if alerts:
            pdf.section_header("Threat Detection Summary")
            pdf.kv_row("Total Alerts:", f"{len(alerts):,}")

            sev_counts = defaultdict(int)
            for a in alerts:
                sev_counts[a.get('severity', 'unknown')] += 1
            for sev in ['critical', 'high', 'medium', 'low']:
                if sev in sev_counts:
                    pdf.kv_row(f"  {sev.upper()}:", str(sev_counts[sev]))
            pdf.ln(2)

            # Alert details table
            if len(alerts) > 0:
                pdf.set_font('Helvetica', 'B', 10)
                pdf.set_fill_color(200, 50, 50)
                pdf.set_text_color(255, 255, 255)
                pdf.cell(30, 7, 'Time', border=1, fill=True, align='C')
                pdf.cell(35, 7, 'Type', border=1, fill=True, align='C')
                pdf.cell(20, 7, 'Severity', border=1, fill=True, align='C')
                pdf.cell(30, 7, 'Source IP', border=1, fill=True, align='C')
                pdf.cell(75, 7, 'Description', border=1, fill=True, align='C', new_x="LMARGIN", new_y="NEXT")

                pdf.set_font('Helvetica', '', 8)
                pdf.set_text_color(30, 30, 30)
                for alert in alerts[:50]:
                    ts = alert.get('timestamp_str', '')
                    atype = alert.get('alert_type', '')[:15]
                    sev = alert.get('severity', '')[:8]
                    src = alert.get('src_ip', '')[:15]
                    desc = alert.get('description', '')[:50]
                    pdf.cell(30, 5, ts, border=1, align='C')
                    pdf.cell(35, 5, atype, border=1, align='C')
                    pdf.cell(20, 5, sev, border=1, align='C')
                    pdf.cell(30, 5, src, border=1, align='C')
                    pdf.cell(75, 5, desc, border=1, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(4)

        # === TOP TALKERS ===
        pdf.section_header("Top Talkers")

        src_ip_counts = defaultdict(int)
        dst_ip_counts = defaultdict(int)
        for pkt in packets:
            src = pkt.get('src_ip')
            dst = pkt.get('dst_ip')
            if src:
                src_ip_counts[src] += 1
            if dst:
                dst_ip_counts[dst] += 1

        pdf.set_font('Helvetica', 'B', 9)
        pdf.set_fill_color(50, 50, 50)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(10, 6, '#', border=1, fill=True, align='C')
        pdf.cell(60, 6, 'Source IP', border=1, fill=True, align='C')
        pdf.cell(25, 6, 'Packets', border=1, fill=True, align='C')
        pdf.cell(10, 6, '#', border=1, fill=True, align='C')
        pdf.cell(60, 6, 'Destination IP', border=1, fill=True, align='C')
        pdf.cell(25, 6, 'Packets', border=1, fill=True, align='C', new_x="LMARGIN", new_y="NEXT")

        pdf.set_font('Helvetica', '', 8)
        pdf.set_text_color(30, 30, 30)
        top_src = sorted(src_ip_counts.items(), key=lambda x: -x[1])[:10]
        top_dst = sorted(dst_ip_counts.items(), key=lambda x: -x[1])[:10]
        for i in range(max(len(top_src), len(top_dst))):
            pdf.cell(10, 5, str(i + 1), border=1, align='C')
            if i < len(top_src):
                pdf.cell(60, 5, top_src[i][0], border=1)
                pdf.cell(25, 5, f'{top_src[i][1]:,}', border=1, align='C')
            else:
                pdf.cell(60, 5, '', border=1)
                pdf.cell(25, 5, '', border=1, align='C')
            pdf.cell(10, 5, str(i + 1), border=1, align='C')
            if i < len(top_dst):
                pdf.cell(60, 5, top_dst[i][0], border=1)
                pdf.cell(25, 5, f'{top_dst[i][1]:,}', border=1, align='C')
            else:
                pdf.cell(60, 5, '', border=1)
                pdf.cell(25, 5, '', border=1, align='C')
            pdf.ln()
        pdf.ln(4)

        # === PACKET TABLE ===
        max_packet_rows = 500
        pdf.add_page()
        pdf.section_header(f"Captured Packets (showing {min(len(packets), max_packet_rows)} of {len(packets):,})")

        col_widths = [12, 22, 38, 38, 16, 18, 46]
        headers = ['#', 'Time', 'Source', 'Destination', 'Proto', 'Length', 'Info']

        pdf.set_font('Helvetica', 'B', 7)
        pdf.set_fill_color(50, 50, 50)
        pdf.set_text_color(255, 255, 255)
        for w, h in zip(col_widths, headers):
            pdf.cell(w, 6, h, border=1, fill=True, align='C')
        pdf.ln()

        pdf.set_font('Helvetica', '', 6)
        pdf.set_text_color(30, 30, 30)
        for i, pkt in enumerate(packets[:max_packet_rows]):
            ts = pkt.get('timestamp_str', '')[:19]
            if ts:
                try:
                    ts = datetime.fromisoformat(ts).strftime('%H:%M:%S')
                except Exception:
                    ts = ts[:8]

            src = pkt.get('src_ip', pkt.get('src_mac', ''))[:20]
            dst = pkt.get('dst_ip', pkt.get('dst_mac', ''))[:20]
            proto = pkt.get('protocol_name', 'Unknown')[:8]
            length = str(pkt.get('packet_length', 0))
            info = _get_info(pkt)[:35]

            # Alternate row shading
            if i % 2 == 0:
                pdf.set_fill_color(245, 245, 245)
                fill = True
            else:
                fill = False

            pdf.cell(col_widths[0], 5, str(i + 1), border=1, align='C', fill=fill)
            pdf.cell(col_widths[1], 5, ts, border=1, align='C', fill=fill)
            pdf.cell(col_widths[2], 5, src, border=1, fill=fill)
            pdf.cell(col_widths[3], 5, dst, border=1, fill=fill)
            pdf.cell(col_widths[4], 5, proto, border=1, align='C', fill=fill)
            pdf.cell(col_widths[5], 5, length, border=1, align='C', fill=fill)
            pdf.cell(col_widths[6], 5, info, border=1, fill=fill, new_x="LMARGIN", new_y="NEXT")

        # === SAVE ===
        save_path = _get_save_path(output_dir)
        pdf.output(save_path)
        logger.info(f"PDF report saved: {save_path}")
        return save_path

    except Exception as e:
        logger.error(f"Failed to generate PDF report: {e}", exc_info=True)
        return None


def _get_save_path(output_dir: Optional[str] = None) -> str:
    """Determine where to save the PDF report."""
    if output_dir and os.path.isdir(output_dir):
        base = output_dir
    else:
        # Try Documents folder, fall back to home
        home = Path.home()
        docs = home / "Documents"
        if docs.is_dir():
            base = str(docs)
        else:
            base = str(home)

    # Create subdirectory
    report_dir = os.path.join(base, "PacketVision_Reports")
    os.makedirs(report_dir, exist_ok=True)

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"PacketVision_Report_{timestamp}.pdf"
    return os.path.join(report_dir, filename)


def _format_bytes(size: int) -> str:
    """Format bytes to human readable."""
    for unit in ['B', 'KB', 'MB', 'GB']:
        if size < 1024:
            return f"{size:.1f} {unit}"
        size /= 1024
    return f"{size:.1f} TB"


def _get_info(pkt: Dict[str, Any]) -> str:
    """Generate info string for packet table."""
    proto = pkt.get('protocol_name', '')
    if proto == 'TCP':
        flags = pkt.get('tcp_flags', '')
        sp = pkt.get('src_port', '')
        dp = pkt.get('dst_port', '')
        return f"{sp}->{dp} [{flags}]"
    elif proto == 'UDP':
        sp = pkt.get('src_port', '')
        dp = pkt.get('dst_port', '')
        return f"{sp}->{dp}"
    elif proto == 'DNS':
        qr = pkt.get('dns_qr', '')
        query = pkt.get('dns_query', '')
        return f"{qr} {query}"
    elif proto == 'HTTP':
        method = pkt.get('http_method', '')
        host = pkt.get('http_host', '')
        return f"{method} {host}"
    elif proto == 'ICMP':
        return pkt.get('icmp_type_name', 'ICMP')
    elif proto == 'ARP':
        return pkt.get('arp_op_name', 'ARP')
    return ''
